### ISSUE TITLE
file INSTALL cannot find dolphin-insync-plugin.desktop

### ISSUE THREAD

**Issue by jdcarvalho** [insynchq/dolphin-insync-plugin#1]
Hi,

I am trying to install this plugin and after do the build with cmake with command

> cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release

and doing it "make" the sofware builts fine

but then "make install" command raises

-- Install configuration: "Release"
CMake Error at cmake_install.cmake:44 (FILE):
  file INSTALL cannot find
  "/opt/dolphin-insync/dolphin-insync-plugin.desktop". 

Could you help me with this?

Thanks in advance

**Comment by luipugs** [comment]
What Linux distribution and version are you using? And what KDE version?

**Comment by jdcarvalho** [comment]
HI luipugs,

I am using Kubuntu 14.04 Kernel Linux 3.13.0-35-generic and KDE 4.13.3

**Comment by luipugs** [comment]
Hi Joao,

There was a file that I forgot to add, please pull the latest commit and retry.

**Comment by luipugs** [comment]
Closed for lack of activity.
